package sec1;
public class UserException1 {
	public static void main(String[] args) {
		try {
			method1();
		} catch (RunException e){
			e.printStackTrace();
		}
	}
	public static void method1() throws RunException { //throw 자동으로 예외를 발생시킬때
		throw new RunException("사용자 예외");
		
	}

}
